name: Dependency-Check SCA Action

on:
  push:
    paths:
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - package.json
      - package-lock.json
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

jobs:
  dependencycheck:
    runs-on: ubuntu-latest
    name: dependency-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'Pilot'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          # args: >
          #   --failOnCVSS 7
          #   --enableRetired
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Dependency-Check report
           path: ${{github.workspace}}/reports
